#!/usr/bin/env python
# -*- coding: utf-8 -*-

# CAVEAT UTILITOR
#
# This file was automatically generated by TatSu.
#
#    https://pypi.python.org/pypi/tatsu/
#
# Any changes you make to it will be overwritten the next time
# the file is generated.


from __future__ import print_function, division, absolute_import, unicode_literals

from tatsu.buffering import Buffer
from tatsu.parsing import Parser
from tatsu.parsing import tatsumasu
from tatsu.util import re, generic_main  # noqa


KEYWORDS = {}


class WewBuffer(Buffer):
    def __init__(
        self,
        text,
        whitespace=None,
        nameguard=None,
        comments_re='{~(\\n|.)*~}',
        eol_comments_re='\\/\\/.*?$',
        ignorecase=None,
        namechars='',
        **kwargs
    ):
        super(WewBuffer, self).__init__(
            text,
            whitespace=whitespace,
            nameguard=nameguard,
            comments_re=comments_re,
            eol_comments_re=eol_comments_re,
            ignorecase=ignorecase,
            namechars=namechars,
            **kwargs
        )


class WewParser(Parser):
    def __init__(
        self,
        whitespace=None,
        nameguard=None,
        comments_re='{~(\\n|.)*~}',
        eol_comments_re='\\/\\/.*?$',
        ignorecase=None,
        left_recursion=True,
        parseinfo=True,
        keywords=None,
        namechars='',
        buffer_class=WewBuffer,
        **kwargs
    ):
        if keywords is None:
            keywords = KEYWORDS
        super(WewParser, self).__init__(
            whitespace=whitespace,
            nameguard=nameguard,
            comments_re=comments_re,
            eol_comments_re=eol_comments_re,
            ignorecase=ignorecase,
            left_recursion=left_recursion,
            parseinfo=parseinfo,
            keywords=keywords,
            namechars=namechars,
            buffer_class=buffer_class,
            **kwargs
        )

    @tatsumasu()
    def _start_(self):  # noqa

        def block0():
            self._function_decl_()
        self._positive_closure(block0)
        self._check_eof()

    @tatsumasu()
    def _types_(self):  # noqa
        self._token('int')

    @tatsumasu()
    def _pointer_(self):  # noqa

        def block0():
            self._token('*')
            self.add_last_node_to_name('@')
        self._positive_closure(block0)

    @tatsumasu()
    def _instance_types_(self):  # noqa
        with self._choice():
            with self._option():
                self._types_()
                self._pointer_()
            with self._option():
                self._types_()
            self._error('no available options')

    @tatsumasu()
    def _typed_variable_(self):  # noqa
        self._instance_types_()
        self.name_last_node('type')
        self._identifier_()
        self.name_last_node('name')
        self.ast._define(
            ['name', 'type'],
            []
        )

    @tatsumasu()
    def _declaration_(self):  # noqa
        with self._choice():
            with self._option():
                self._types_()
                self.name_last_node('type')
                self._pointer_()
                self.name_last_node('pt')
                self._identifier_()
                self.name_last_node('name')
                self._token(';')
                self._constant('pointer')
                self.name_last_node('ref')
            with self._option():
                self._types_()
                self.name_last_node('type')
                self._identifier_()
                self.name_last_node('name')
                self._token('[')
                self._integer_()
                self.name_last_node('pt')
                self._token(']')
                self._token(';')
                self._constant('list')
                self.name_last_node('ref')
            with self._option():
                self._types_()
                self.name_last_node('type')
                self._identifier_()
                self.name_last_node('name')
            self._error('no available options')
        self.ast._define(
            ['name', 'pt', 'ref', 'type'],
            []
        )

    @tatsumasu()
    def _function_decl_(self):  # noqa
        self._instance_types_()
        self.name_last_node('type')
        self._identifier_()
        self.name_last_node('name')
        self._token('(')

        def sep3():
            self._token(',')

        def block3():
            self._typed_variable_()
        self._gather(block3, sep3)
        self.name_last_node('params')
        self._token(')')
        self._token('{')
        self._multi_statements_()
        self.name_last_node('stat')
        self._token('}')
        self.ast._define(
            ['name', 'params', 'stat', 'type'],
            []
        )

    @tatsumasu()
    def _multi_statements_(self):  # noqa

        def block0():
            self._statement_()
            self.add_last_node_to_name('@')
        self._closure(block0)

    @tatsumasu()
    def _statement_(self):  # noqa
        with self._choice():
            with self._option():
                self._expression_stmt_()
            with self._option():
                self._if_statement_()
            with self._option():
                self._loop_statement_()
            with self._option():
                self._return_stmt_()
            with self._option():
                self._declaration_()
            self._error('no available options')

    @tatsumasu()
    def _expression_stmt_(self):  # noqa
        self._expression_()
        self._token(';')

    @tatsumasu()
    def _return_stmt_(self):  # noqa
        self._token('return')
        self._expression_()
        self.name_last_node('expr')
        self._token(';')
        self.ast._define(
            ['expr'],
            []
        )

    @tatsumasu()
    def _if_statement_(self):  # noqa
        self._token('if')
        self._cut()
        self._token('(')
        self._expression_()
        self.name_last_node('expr')
        self._token(')')
        self._token('{')
        self._multi_statements_()
        self.name_last_node('stat')
        self._token('}')
        with self._optional():
            self._token('else')
            self._multi_statements_()
            self.name_last_node('else_')
        self.ast._define(
            ['else_', 'expr', 'stat'],
            []
        )

    @tatsumasu()
    def _loop_statement_(self):  # noqa
        with self._choice():
            with self._option():
                self._token('while')
                self.name_last_node('type')
                self._cut()
                self._token('(')
                self._expression_()
                self.name_last_node('expr')
                self._token(')')
                self._token('{')
                self._multi_statements_()
                self.name_last_node('stat')
                self._token('}')
            with self._option():
                self._token('do')
                self.name_last_node('type')
                self._cut()
                self._token('{')
                self._multi_statements_()
                self.name_last_node('stat')
                self._token('}')
                self._token('while')
                self._token('(')
                self._expression_()
                self.name_last_node('expr')
                self._token(')')
                self._token(';')
            self._error('no available options')
        self.ast._define(
            ['expr', 'stat', 'type'],
            []
        )

    @tatsumasu()
    def _primary_expression_(self):  # noqa
        with self._choice():
            with self._option():
                self._identifier_()
            with self._option():
                self._literal_()
            with self._option():
                self._token('(')
                self._expression_()
                self._token(')')
            self._error('no available options')

    @tatsumasu()
    def _function_call_(self):  # noqa
        self._identifier_()
        self.name_last_node('name')
        self._token('(')

        def sep2():
            self._token(',')

        def block2():
            self._expression_()
        self._gather(block2, sep2)
        self.name_last_node('vars')
        self._token(')')
        self.ast._define(
            ['name', 'vars'],
            []
        )

    @tatsumasu()
    def _postfix_expression_(self):  # noqa
        with self._choice():
            with self._option():
                self._expression_()
                self.name_last_node('expr')
                self._token('[')
                self._expression_()
                self.name_last_node('val')
                self._token(']')
                self._constant('list')
                self.name_last_node('op')
            with self._option():
                self._expression_()
                self.name_last_node('expr')
                self._token('++')
                self.name_last_node('op')
            with self._option():
                self._expression_()
                self.name_last_node('expr')
                self._token('--')
                self.name_last_node('op')
            self._error('no available options')
        self.ast._define(
            ['expr', 'op', 'val'],
            []
        )

    @tatsumasu()
    def _unary_expression_(self):  # noqa
        with self._choice():
            with self._option():
                self._token('--')
                self.name_last_node('op')
                self._cut()
                self._expression_()
                self.name_last_node('expr')
            with self._option():
                self._token('++')
                self.name_last_node('op')
                self._cut()
                self._expression_()
                self.name_last_node('expr')
            with self._option():
                self._un_op_()
                self.name_last_node('op')
                self._cut()
                self._expression_()
                self.name_last_node('expr')
            self._error('no available options')
        self.ast._define(
            ['expr', 'op'],
            []
        )

    @tatsumasu()
    def _un_op_(self):  # noqa
        with self._choice():
            with self._option():
                self._token('*')
            with self._option():
                self._token('-')
            with self._option():
                self._token('+')
            with self._option():
                self._token('~')
            with self._option():
                self._token('!')
            self._error('expecting one of: ! * + - ~')

    @tatsumasu()
    def _mult_expression_(self):  # noqa
        with self._choice():
            with self._option():
                self._expression_()
                self.name_last_node('left')
                self._token('*')
                self.name_last_node('op')
                self._cut()
                self._expression_()
                self.name_last_node('right')
            with self._option():
                self._expression_()
                self.name_last_node('left')
                self._token('/')
                self.name_last_node('op')
                self._cut()
                self._expression_()
                self.name_last_node('right')
            self._error('no available options')
        self.ast._define(
            ['left', 'op', 'right'],
            []
        )

    @tatsumasu()
    def _add_expression_(self):  # noqa
        with self._choice():
            with self._option():
                self._expression_()
                self.name_last_node('left')
                self._token('+')
                self.name_last_node('op')
                self._cut()
                self._expression_()
                self.name_last_node('right')
            with self._option():
                self._expression_()
                self.name_last_node('left')
                self._token('-')
                self.name_last_node('op')
                self._cut()
                self._expression_()
                self.name_last_node('right')
            self._error('no available options')
        self.ast._define(
            ['left', 'op', 'right'],
            []
        )

    @tatsumasu()
    def _shift_expression_(self):  # noqa
        with self._choice():
            with self._option():
                self._expression_()
                self.name_last_node('left')
                self._token('<<')
                self.name_last_node('op')
                self._cut()
                self._expression_()
                self.name_last_node('right')
            with self._option():
                self._expression_()
                self.name_last_node('left')
                self._token('>>')
                self.name_last_node('op')
                self._cut()
                self._expression_()
                self.name_last_node('right')
            self._error('no available options')
        self.ast._define(
            ['left', 'op', 'right'],
            []
        )

    @tatsumasu()
    def _relative_expression_(self):  # noqa
        with self._choice():
            with self._option():
                self._expression_()
                self.name_last_node('left')
                self._token('>')
                self.name_last_node('op')
                self._cut()
                self._expression_()
                self.name_last_node('right')
            with self._option():
                self._expression_()
                self.name_last_node('left')
                self._token('<')
                self.name_last_node('op')
                self._cut()
                self._expression_()
                self.name_last_node('right')
            with self._option():
                self._expression_()
                self.name_last_node('left')
                self._token('>=')
                self.name_last_node('op')
                self._cut()
                self._expression_()
                self.name_last_node('right')
            with self._option():
                self._expression_()
                self.name_last_node('left')
                self._token('<=')
                self.name_last_node('op')
                self._cut()
                self._expression_()
                self.name_last_node('right')
            self._error('no available options')
        self.ast._define(
            ['left', 'op', 'right'],
            []
        )

    @tatsumasu()
    def _equality_expression_(self):  # noqa
        with self._choice():
            with self._option():
                self._expression_()
                self.name_last_node('left')
                self._token('==')
                self.name_last_node('op')
                self._cut()
                self._expression_()
                self.name_last_node('right')
            with self._option():
                self._expression_()
                self.name_last_node('left')
                self._token('!=')
                self.name_last_node('op')
                self._cut()
                self._expression_()
                self.name_last_node('right')
            self._error('no available options')
        self.ast._define(
            ['left', 'op', 'right'],
            []
        )

    @tatsumasu()
    def _and_expression_(self):  # noqa
        self._expression_()
        self.name_last_node('left')
        self._token('&')
        self.name_last_node('op')
        self._cut()
        self._expression_()
        self.name_last_node('right')
        self.ast._define(
            ['left', 'op', 'right'],
            []
        )

    @tatsumasu()
    def _xor_expression_(self):  # noqa
        self._expression_()
        self.name_last_node('left')
        self._token('^')
        self.name_last_node('op')
        self._cut()
        self._expression_()
        self.name_last_node('right')
        self.ast._define(
            ['left', 'op', 'right'],
            []
        )

    @tatsumasu()
    def _or_expression_(self):  # noqa
        self._expression_()
        self.name_last_node('left')
        self._token('|')
        self.name_last_node('op')
        self._cut()
        self._expression_()
        self.name_last_node('right')
        self.ast._define(
            ['left', 'op', 'right'],
            []
        )

    @tatsumasu()
    def _land_expression_(self):  # noqa
        self._expression_()
        self.name_last_node('left')
        self._token('&&')
        self.name_last_node('op')
        self._cut()
        self._expression_()
        self.name_last_node('right')
        self.ast._define(
            ['left', 'op', 'right'],
            []
        )

    @tatsumasu()
    def _lor_expression_(self):  # noqa
        self._expression_()
        self.name_last_node('left')
        self._token('||')
        self.name_last_node('op')
        self._cut()
        self._expression_()
        self.name_last_node('right')
        self.ast._define(
            ['left', 'op', 'right'],
            []
        )

    @tatsumasu()
    def _assign_expression_(self):  # noqa
        self._expression_()
        self.name_last_node('left')
        self._token(':=')
        self.name_last_node('op')
        self._cut()
        self._expression_()
        self.name_last_node('right')
        self.ast._define(
            ['left', 'op', 'right'],
            []
        )

    @tatsumasu()
    def _expression_(self):  # noqa
        with self._choice():
            with self._option():
                self._assign_expression_()
            with self._option():
                self._lor_expression_()
            with self._option():
                self._land_expression_()
            with self._option():
                self._or_expression_()
            with self._option():
                self._xor_expression_()
            with self._option():
                self._and_expression_()
            with self._option():
                self._equality_expression_()
            with self._option():
                self._relative_expression_()
            with self._option():
                self._shift_expression_()
            with self._option():
                self._add_expression_()
            with self._option():
                self._mult_expression_()
            with self._option():
                self._unary_expression_()
            with self._option():
                self._postfix_expression_()
            with self._option():
                self._function_call_()
            with self._option():
                self._primary_expression_()
            self._error('no available options')

    @tatsumasu()
    def _integer_(self):  # noqa
        self._pattern(r'\d+')

    @tatsumasu()
    def _string_(self):  # noqa
        self._pattern(r'".+"')

    @tatsumasu()
    def _char_(self):  # noqa
        self._pattern(r"'.'")

    @tatsumasu()
    def _literal_(self):  # noqa
        with self._choice():
            with self._option():
                self._integer_()
                self.name_last_node('val')
                self._constant('int')
                self.name_last_node('type')
            with self._option():
                self._string_()
                self.name_last_node('val')
                self._constant('str')
                self.name_last_node('type')
            with self._option():
                self._char_()
                self.name_last_node('val')
                self._constant('char')
                self.name_last_node('type')
            self._error('no available options')
        self.ast._define(
            ['type', 'val'],
            []
        )

    @tatsumasu()
    def _identifier_(self):  # noqa
        self._pattern(r'[A-Za-z]\w+')


class WewSemantics(object):
    def start(self, ast):  # noqa
        return ast

    def types(self, ast):  # noqa
        return ast

    def pointer(self, ast):  # noqa
        return ast

    def instance_types(self, ast):  # noqa
        return ast

    def typed_variable(self, ast):  # noqa
        return ast

    def declaration(self, ast):  # noqa
        return ast

    def function_decl(self, ast):  # noqa
        return ast

    def multi_statements(self, ast):  # noqa
        return ast

    def statement(self, ast):  # noqa
        return ast

    def expression_stmt(self, ast):  # noqa
        return ast

    def return_stmt(self, ast):  # noqa
        return ast

    def if_statement(self, ast):  # noqa
        return ast

    def loop_statement(self, ast):  # noqa
        return ast

    def primary_expression(self, ast):  # noqa
        return ast

    def function_call(self, ast):  # noqa
        return ast

    def postfix_expression(self, ast):  # noqa
        return ast

    def unary_expression(self, ast):  # noqa
        return ast

    def un_op(self, ast):  # noqa
        return ast

    def mult_expression(self, ast):  # noqa
        return ast

    def add_expression(self, ast):  # noqa
        return ast

    def shift_expression(self, ast):  # noqa
        return ast

    def relative_expression(self, ast):  # noqa
        return ast

    def equality_expression(self, ast):  # noqa
        return ast

    def and_expression(self, ast):  # noqa
        return ast

    def xor_expression(self, ast):  # noqa
        return ast

    def or_expression(self, ast):  # noqa
        return ast

    def land_expression(self, ast):  # noqa
        return ast

    def lor_expression(self, ast):  # noqa
        return ast

    def assign_expression(self, ast):  # noqa
        return ast

    def expression(self, ast):  # noqa
        return ast

    def integer(self, ast):  # noqa
        return ast

    def string(self, ast):  # noqa
        return ast

    def char(self, ast):  # noqa
        return ast

    def literal(self, ast):  # noqa
        return ast

    def identifier(self, ast):  # noqa
        return ast


def main(filename, startrule, **kwargs):
    with open(filename) as f:
        text = f.read()
    parser = WewParser()
    return parser.parse(text, startrule, filename=filename, **kwargs)


if __name__ == '__main__':
    import json
    from tatsu.util import asjson

    ast = generic_main(main, WewParser, name='Wew')
    print('AST:')
    print(ast)
    print()
    print('JSON:')
    print(json.dumps(asjson(ast), indent=2))
    print()
