#!/usr/bin/env python
# -*- coding: utf-8 -*-

# CAVEAT UTILITOR
#
# This file was automatically generated by TatSu.
#
#    https://pypi.python.org/pypi/tatsu/
#
# Any changes you make to it will be overwritten the next time
# the file is generated.


from __future__ import print_function, division, absolute_import, unicode_literals

from tatsu.buffering import Buffer
from tatsu.parsing import Parser
from tatsu.parsing import tatsumasu
from tatsu.util import re, generic_main  # noqa


KEYWORDS = {}


class WewBuffer(Buffer):
    def __init__(
        self,
        text,
        whitespace=None,
        nameguard=None,
        comments_re=None,
        eol_comments_re=None,
        ignorecase=None,
        namechars='',
        **kwargs
    ):
        super(WewBuffer, self).__init__(
            text,
            whitespace=whitespace,
            nameguard=nameguard,
            comments_re=comments_re,
            eol_comments_re=eol_comments_re,
            ignorecase=ignorecase,
            namechars=namechars,
            **kwargs
        )


class WewParser(Parser):
    def __init__(
        self,
        whitespace=None,
        nameguard=None,
        comments_re=None,
        eol_comments_re=None,
        ignorecase=None,
        left_recursion=True,
        parseinfo=True,
        keywords=None,
        namechars='',
        buffer_class=WewBuffer,
        **kwargs
    ):
        if keywords is None:
            keywords = KEYWORDS
        super(WewParser, self).__init__(
            whitespace=whitespace,
            nameguard=nameguard,
            comments_re=comments_re,
            eol_comments_re=eol_comments_re,
            ignorecase=ignorecase,
            left_recursion=left_recursion,
            parseinfo=parseinfo,
            keywords=keywords,
            namechars=namechars,
            buffer_class=buffer_class,
            **kwargs
        )

    @tatsumasu()
    def _start_(self):  # noqa

        def block0():
            self._function_decl_()
        self._positive_closure(block0)
        self._check_eof()

    @tatsumasu()
    def _types_(self):  # noqa
        self._token('int')

    @tatsumasu()
    def _pointer_(self):  # noqa

        def block0():
            self._token('*')
            self.add_last_node_to_name('@')
        self._positive_closure(block0)

    @tatsumasu()
    def _declare_types_(self):  # noqa
        with self._choice():
            with self._option():
                self._types_()
                self.name_last_node('typ')
                self._pointer_()
                self.name_last_node('pc')
            with self._option():
                self._types_()
                self.name_last_node('typ')
                self._token('[')
                self._integer_()
                self.name_last_node('len')
                self._token(']')
            with self._option():
                self._types_()
                self.name_last_node('typ')
            self._error('no available options')
        self.ast._define(
            ['len', 'pc', 'typ'],
            []
        )

    @tatsumasu()
    def _instance_types_(self):  # noqa
        with self._choice():
            with self._option():
                self._types_()
                self._pointer_()
            with self._option():
                self._types_()
            self._error('no available options')

    @tatsumasu()
    def _typed_variable_(self):  # noqa
        self._instance_types_()
        self.name_last_node('type')
        self._var_name_()
        self.name_last_node('name')
        self.ast._define(
            ['name', 'type'],
            []
        )

    @tatsumasu()
    def _declaration_(self):  # noqa
        self._declare_types_()
        self.name_last_node('typ')
        self._var_name_()
        self.name_last_node('name')
        self._token(';')
        self.ast._define(
            ['name', 'typ'],
            []
        )

    @tatsumasu()
    def _function_decl_(self):  # noqa
        self._instance_types_()
        self.name_last_node('typ')
        self._var_name_()
        self.name_last_node('name')
        self._token('(')
        self._cut()

        def sep3():
            self._token(',')

        def block3():
            self._typed_variable_()
        self._positive_gather(block3, sep3)
        self.name_last_node('params')
        self._token(')')
        self._scope_()
        self.name_last_node('exp')
        self.ast._define(
            ['exp', 'name', 'params', 'typ'],
            []
        )

    @tatsumasu()
    def _statement_(self):  # noqa
        with self._choice():
            with self._option():
                self._if_statement_()
            with self._option():
                self._loop_statement_()
            with self._option():
                self._assignment_()
            with self._option():
                self._function_call_stmt_()
            with self._option():
                self._return_stmt_()
            with self._option():
                self._declaration_()
            with self._option():
                self._scope_()
            self._error('no available options')

    @tatsumasu()
    def _return_stmt_(self):  # noqa
        self._token('return')
        self._expression_()
        self.name_last_node('expr')
        self._token(';')
        self.ast._define(
            ['expr'],
            []
        )

    @tatsumasu()
    def _if_statement_(self):  # noqa
        with self._choice():
            with self._option():
                self._token('if')
                self._token('(')
                self._expression_()
                self.name_last_node('expr')
                self._token(')')
                self._statement_()
                self.name_last_node('stat')
                self._void()
                self.name_last_node('el')
            with self._option():
                self._token('if')
                self._token('(')
                self._expression_()
                self.name_last_node('expr')
                self._token(')')
                self._statement_()
                self.name_last_node('stat')
                self._token('else')
                self._cut()
                self._statement_()
                self.name_last_node('el')
            self._error('no available options')
        self.ast._define(
            ['el', 'expr', 'stat'],
            []
        )

    @tatsumasu()
    def _loop_statement_(self):  # noqa
        with self._choice():
            with self._option():
                self._token('while')
                self.name_last_node('type')
                self._cut()
                self._token('(')
                self._expression_()
                self.name_last_node('expr')
                self._token(')')
                self._statement_()
                self.name_last_node('stat')
            with self._option():
                self._token('do')
                self.name_last_node('type')
                self._cut()
                self._statement_()
                self.name_last_node('stat')
                self._token('while')
                self._token('(')
                self._expression_()
                self.name_last_node('expr')
                self._token(')')
                self._token(';')
            self._error('no available options')
        self.ast._define(
            ['expr', 'stat', 'type'],
            []
        )

    @tatsumasu()
    def _scope_(self):  # noqa
        self._token('{')

        def block0():
            self._statement_()
        self._positive_closure(block0)
        self._token('}')

    @tatsumasu()
    def _assignment_(self):  # noqa
        self._expression_()
        self.name_last_node('left')
        self._token(':=')
        self._expression_()
        self.name_last_node('right')
        self._token(';')
        self.ast._define(
            ['left', 'right'],
            []
        )

    @tatsumasu()
    def _function_call_(self):  # noqa
        self._var_name_()
        self.name_last_node('name')
        self._token('(')
        self._cut()

        def sep2():
            self._token(',')

        def block2():
            self._expression_()
        self._gather(block2, sep2)
        self.name_last_node('vars')
        self._token(')')
        self.ast._define(
            ['name', 'vars'],
            []
        )

    @tatsumasu()
    def _function_call_stmt_(self):  # noqa
        self._function_call_()
        self._token(';')

    @tatsumasu()
    def _expression_(self):  # noqa
        with self._choice():
            with self._option():
                self._function_call_()
            with self._option():
                self._comparison_stmt_()
            with self._option():
                self._postfix_expression_()
            with self._option():
                self._prefix_expression_()
            with self._option():
                self._var_name_()
            with self._option():
                self._literal_()
            with self._option():
                self._infix_expression_()
            with self._option():
                self._token('(')
                self._expression_()
                self._token(')')
            self._error('no available options')

    @tatsumasu()
    def _comparisons_(self):  # noqa
        with self._choice():
            with self._option():
                self._token('==')
            with self._option():
                self._token('!=')
            with self._option():
                self._token('>')
            with self._option():
                self._token('<')
            with self._option():
                self._token('<=')
            with self._option():
                self._token('>=')
            self._error('expecting one of: != < <= == > >=')

    @tatsumasu()
    def _comparison_stmt_(self):  # noqa
        self._expression_()
        self.name_last_node('left')
        with self._group():
            with self._choice():
                with self._option():
                    self._token('==')
                with self._option():
                    self._token('!=')
                with self._option():
                    self._token('>')
                with self._option():
                    self._token('<')
                with self._option():
                    self._token('<=')
                with self._option():
                    self._token('>=')
                self._error('expecting one of: != < <= == > >=')
        self.name_last_node('op')
        self._expression_()
        self.name_last_node('right')
        self.ast._define(
            ['left', 'op', 'right'],
            []
        )

    @tatsumasu()
    def _prefix_expression_(self):  # noqa
        with self._choice():
            with self._option():
                self._token('*')
                self.name_last_node('op')
                self._cut()
                self._expression_()
                self.name_last_node('expr')
            with self._option():
                self._token('--')
                self.name_last_node('op')
                self._cut()
                self._expression_()
                self.name_last_node('expr')
            with self._option():
                self._token('++')
                self.name_last_node('op')
                self._cut()
                self._expression_()
                self.name_last_node('expr')
            self._error('no available options')
        self.ast._define(
            ['expr', 'op'],
            []
        )

    @tatsumasu()
    def _postfix_expression_(self):  # noqa
        with self._choice():
            with self._option():
                self._expression_()
                self.name_last_node('expr')
                self._token('[')
                self._cut()
                self._expression_()
                self._token(']')
            with self._option():
                self._expression_()
                self.name_last_node('expr')
                self._token('++')
                self.name_last_node('op')
            with self._option():
                self._expression_()
                self.name_last_node('expr')
                self._token('--')
                self.name_last_node('op')
            self._error('no available options')
        self.ast._define(
            ['expr', 'op'],
            []
        )

    @tatsumasu()
    def _infix_expression_(self):  # noqa
        with self._choice():
            with self._option():
                self._expression_()
                self.name_last_node('left')
                self._token('+')
                self.name_last_node('op')
                self._expression_()
                self.name_last_node('right')
            with self._option():
                self._expression_()
                self.name_last_node('left')
                self._token('-')
                self.name_last_node('op')
                self._expression_()
                self.name_last_node('right')
            with self._option():
                self._mul_expr_()
            self._error('no available options')
        self.ast._define(
            ['left', 'op', 'right'],
            []
        )

    @tatsumasu()
    def _mul_expr_(self):  # noqa
        with self._choice():
            with self._option():
                self._expression_()
                self.name_last_node('left')
                self._token('*')
                self.name_last_node('op')
                self._expression_()
                self.name_last_node('right')
            with self._option():
                self._expression_()
                self.name_last_node('left')
                self._token('/')
                self.name_last_node('op')
                self._expression_()
                self.name_last_node('right')
            self._error('no available options')
        self.ast._define(
            ['left', 'op', 'right'],
            []
        )

    @tatsumasu()
    def _integer_(self):  # noqa
        self._pattern(r'\d+')

    @tatsumasu()
    def _string_(self):  # noqa
        self._pattern(r'".+"')

    @tatsumasu()
    def _char_(self):  # noqa
        self._pattern(r"'.'")

    @tatsumasu()
    def _literal_(self):  # noqa
        with self._choice():
            with self._option():
                self._integer_()
            with self._option():
                self._string_()
            with self._option():
                self._char_()
            self._error('no available options')

    @tatsumasu()
    def _var_name_(self):  # noqa
        self._pattern(r'\w+')


class WewSemantics(object):
    def start(self, ast):  # noqa
        return ast

    def types(self, ast):  # noqa
        return ast

    def pointer(self, ast):  # noqa
        return ast

    def declare_types(self, ast):  # noqa
        return ast

    def instance_types(self, ast):  # noqa
        return ast

    def typed_variable(self, ast):  # noqa
        return ast

    def declaration(self, ast):  # noqa
        return ast

    def function_decl(self, ast):  # noqa
        return ast

    def statement(self, ast):  # noqa
        return ast

    def return_stmt(self, ast):  # noqa
        return ast

    def if_statement(self, ast):  # noqa
        return ast

    def loop_statement(self, ast):  # noqa
        return ast

    def scope(self, ast):  # noqa
        return ast

    def assignment(self, ast):  # noqa
        return ast

    def function_call(self, ast):  # noqa
        return ast

    def function_call_stmt(self, ast):  # noqa
        return ast

    def expression(self, ast):  # noqa
        return ast

    def comparisons(self, ast):  # noqa
        return ast

    def comparison_stmt(self, ast):  # noqa
        return ast

    def prefix_expression(self, ast):  # noqa
        return ast

    def postfix_expression(self, ast):  # noqa
        return ast

    def infix_expression(self, ast):  # noqa
        return ast

    def mul_expr(self, ast):  # noqa
        return ast

    def integer(self, ast):  # noqa
        return ast

    def string(self, ast):  # noqa
        return ast

    def char(self, ast):  # noqa
        return ast

    def literal(self, ast):  # noqa
        return ast

    def var_name(self, ast):  # noqa
        return ast


def main(filename, startrule, **kwargs):
    with open(filename) as f:
        text = f.read()
    parser = WewParser()
    return parser.parse(text, startrule, filename=filename, **kwargs)


if __name__ == '__main__':
    import json
    from tatsu.util import asjson

    ast = generic_main(main, WewParser, name='Wew')
    print('AST:')
    print(ast)
    print()
    print('JSON:')
    print(json.dumps(asjson(ast), indent=2))
    print()
